PACKET_SYNC_BYTE = 0xAA
PACKET_CMD_DATA = 0xAD
PACKET_CMD_ERR = 0xAE

PACKET_SYNC_INDEX = 0
PACKET_SYNC_LEN = 1
PACKET_LENGTH_INDEX = PACKET_SYNC_INDEX + PACKET_SYNC_LEN
PACKET_LENGTH_LEN = 2
PACKET_HEADER_LEN = PACKET_SYNC_LEN + PACKET_LENGTH_LEN
PACKET_PROTOCOL_INDEX = PACKET_HEADER_LEN
PACKET_PROTOCOL_LEN = 1
PACKET_TYPE_INDEX = PACKET_PROTOCOL_INDEX + PACKET_PROTOCOL_LEN
PACKET_TYPE_LEN = 1
PACKET_CMD_INDEX = PACKET_TYPE_INDEX + PACKET_TYPE_LEN
PACKET_CMD_LEN = 1
PACKET_PAYLOAD_LENGHT_INDEX = PACKET_CMD_INDEX + PACKET_CMD_LEN
PACKET_PAYLOAD_LENGHT_LEN = 2
PACKET_PAYLOAD_INDEX = PACKET_PAYLOAD_LENGHT_INDEX + PACKET_PAYLOAD_LENGHT_LEN
PACKET_CHECKSUM_LEN = 2

PAYLOAD_RPM_INDEX = 0
PAYLOAD_RPM_LEN = 1
PAYLOAD_ANGLE_OFFSET_INDEX = PAYLOAD_RPM_INDEX + PAYLOAD_RPM_LEN
PAYLOAD_ANGLE_OFFSET_LEN = 2
PAYLOAD_ANGLE_START_INDEX = PAYLOAD_ANGLE_OFFSET_INDEX + PAYLOAD_ANGLE_OFFSET_LEN
PAYLOAD_ANGLE_START_LEN = 2
PAYLOAD_ANGLE_END_INDEX = PAYLOAD_ANGLE_START_INDEX + PAYLOAD_ANGLE_START_LEN
PAYLOAD_ANGLE_END_LEN = 2
PAYLOAD_DATA_INDEX = PAYLOAD_ANGLE_END_INDEX + PAYLOAD_ANGLE_END_LEN

PAYLOAD_DATA_PER_ANGLE_SIZE = 3

ANGLE_SCALE_FACTOR = 0.01 #degrees
DISTANCE_SCALE_FACTOR = 0.25 / 1000  #meters

LASERSCAN_RANGE_MIN = 0.05 #meters
LASERSCAN_RANGE_MAX = 12.0 #meters

DEFAULT_SCAN_TIME = 0.1  # fallback in case rpm is zero or invalid

SECONDS_PER_MINUTE = 60.0

